tools:
    external_code_coverage:
        timeout: 600
filter:
    paths: [src/*]
checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php:
            version: 5.5.12

    