<?php
/**
 * Created by PhpStorm.
 * User: adamgrabek
 * Date: 04/10/14
 * Time: 21:52
 */

namespace AGmakonts\STL\DateTime\Exception;


use Exception;

class InvalidMonthException extends \InvalidArgumentException
{
    public function __construct($message = "", $code = 0, Exception $previous = NULL)
    {
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }

} 